from setuptools import setup, find_packages

setup(
    name='fprintx',  
    version='0.0.1',  
    packages=find_packages(), 
    description='A minimal Python utility for clean, aligned debug printing',
    long_description=open('README.md').read(),  
    long_description_content_type='text/markdown',
    author='Programming-Sai',  
    url='https://github.com/Programming-Sai/fprintx.git',  
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'License :: OSI Approved :: MIT License',
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Environment :: No Input/Output (Daemon)',
    ],
    python_requires='>=3.6',  
    keywords='debug print utility, fprintx, formatting',
    license='MIT',
    include_package_data=True,
)
